[package]
name = 'system_shutdown'
version = '1.0.0'
authors = ['Silvio Clecio (silvioprog) <silvioprog@gmail.com>']
license = 'MIT/Apache-2.0'
description = 'Rust library for shut down/reboot the system.'
homepage = 'https://github.com/risoflora/system_shutdown'
repository = 'https://github.com/risoflora/system_shutdown.git'
readme = 'README.md'
keywords = [
    'system',
    'shutdown',
    'reboot',
]
categories = [
    'system-shutdown',
    'system-rebooting',
    'machine-shutdown',
    'machine-reboot',
]

[dependencies]
[target."cfg(windows)".dependencies.winapi]
version = '0.3'
features = [
    'errhandlingapi',
    'processthreadsapi',
    'reason',
    'securitybaseapi',
    'winbase',
    'winerror',
    'winnt',
    'winuser',
]
